name: Code checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]

env:
  TEST_SLN: "cinema_db.sln"

jobs:
  Build:
    runs-on: ubuntu-latest
#    concurrency:
#      cancel-in-progress: false
#      group: ${{ github.workflow }}-Test
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore $TEST_SLN

    - name: Build
      run: dotnet build --no-restore /nowarn:MSB3246 $TEST_SLN

    - name: Write secret MySQL login details to file
      run: echo ${{ secrets.MYSQL_LOGIN_DETAILS }} >> secret_mysql_login.txt

    - name: Test
      if: ${{ false }}
      run: dotnet test --no-build --verbosity normal $TEST_SLN

  Lint_Csharp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x

    - name: Install Roslynator analyzer
      run: dotnet tool install -g roslynator.dotnet.cli

    - name: Run Roslynator analyzer
      run: roslynator analyze -v detailed $TEST_SLN

  Lint_SQL:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3.3.0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"

      - name: Install packages for python
        run: python -m pip install sqlfluff>=2.0.5

      - name: Run sqlfluff linter
        run: sqlfluff lint -v
